global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "podman"
    static_configs:
      - targets: ["localhost:9882"]

remote_write:
  - url: https://prometheus-prod-65-prod-eu-west-2.grafana.net/api/prom/push
    authorization:
      signing_token: "<SIGNING_TOKEN>"